#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ "tas-adapter-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
spec:
  commonName: #@ "*.tas-adapter.{}".format(data.values.ingress.domain)
  dnsNames:
  - #@ "*.tas-adapter.{}".format(data.values.ingress.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: #@ "tas-adapter-{}".format(data.values.ingress.contour_tls_secret)
