#@data/values
---
tanzunet:
  username: user@example.com
  password:
ingress:
  domain: example.com
  contour_tls_namespace: tanzu-system-ingress
  contour_tls_secret: contour-tls-delegation-cert
container_registry:
  hostname: harbor.example.com
  username: admin
  password: 
default_app_memory_allocation: 1000